"""Progress storage, kept in its own database file.

The vocabulary (vocab.db) is opened read-only elsewhere and never written to;
everything this app learns about you lives here in data/progress.db.

Two rules drive the design:

* **Breadth first.** The point is to get past 5,000 words seen, so due reviews
  are never allowed to eat the whole day. MIN_NEW of the daily goal (60 of 100)
  is reserved for words never seen before, and if fewer reviews are due than
  there is room for, the leftover goes to new words too.

* **A card counts once a day.** Answering 不认识 puts a word back in the same
  session, which is relearning, not progress. The daily number is therefore
  COUNT(DISTINCT entry_id) rather than a running tally -- derived, so it cannot
  drift out of step with the reviews it summarises.
"""
import json
import random
import re
import sqlite3
import threading
import time
from datetime import date, timedelta
from pathlib import Path

import srs

DATA_DIR = Path(__file__).resolve().parent / "data"
DB_PATH = DATA_DIR / "progress.db"

DAILY_GOAL = 100
MIN_NEW = 60              # of the daily goal, reserved for unseen words
EXTRA_SIZE = 30           # an optional extra round once the day's goal is met
EXTRA_NEW = 30            # all new words: the round is for breadth, not review
BUSY_TIMEOUT_MS = 5000

SCHEMA = """
CREATE TABLE IF NOT EXISTS cards (
    entry_id  INTEGER PRIMARY KEY,
    reps      INTEGER NOT NULL DEFAULT 0,
    interval  INTEGER NOT NULL DEFAULT 0,   -- days
    ease      REAL    NOT NULL DEFAULT 2.5,
    due       TEXT    NOT NULL,             -- YYYY-MM-DD
    lapses    INTEGER NOT NULL DEFAULT 0,
    first_seen TEXT   NOT NULL,
    last_seen TEXT    NOT NULL
);

-- token is generated by the client, one per card presentation. Replaying a
-- grade (double click, retry after a dropped response) hits the primary key
-- and changes nothing.
CREATE TABLE IF NOT EXISTS reviews (
    token    TEXT PRIMARY KEY,
    entry_id INTEGER NOT NULL,
    day      TEXT    NOT NULL,
    grade    TEXT    NOT NULL,
    was_new  INTEGER NOT NULL DEFAULT 0,
    ts       REAL    NOT NULL
);

CREATE TABLE IF NOT EXISTS daily (
    day        TEXT PRIMARY KEY,
    goal       INTEGER NOT NULL DEFAULT 100,
    celebrated INTEGER NOT NULL DEFAULT 0
);

-- One row per completed extra round.  The client keeps the same token when a
-- request is retried, so a dropped response or double click cannot add two
-- stickers for one round.
CREATE TABLE IF NOT EXISTS extra_rounds (
    token TEXT PRIMARY KEY,
    day   TEXT    NOT NULL,
    size  INTEGER NOT NULL,
    ts    REAL    NOT NULL
);

CREATE INDEX IF NOT EXISTS i_due       ON cards(due);
CREATE INDEX IF NOT EXISTS i_interval  ON cards(interval);
CREATE INDEX IF NOT EXISTS i_day_entry ON reviews(day, entry_id);
CREATE INDEX IF NOT EXISTS i_extra_day ON extra_rounds(day);
"""

_local = threading.local()


def today():
    return date.today().isoformat()


def conn():
    """One connection per thread; sqlite's own busy timeout is enough here."""
    c = getattr(_local, "conn", None)
    if c is None:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        c = sqlite3.connect(str(DB_PATH), timeout=BUSY_TIMEOUT_MS / 1000.0)
        c.row_factory = sqlite3.Row
        c.execute("PRAGMA journal_mode=WAL")
        c.execute("PRAGMA busy_timeout=%d" % BUSY_TIMEOUT_MS)
        c.executescript(SCHEMA)
        _local.conn = c
    return c


def init():
    conn()


# ------------------------------------------------------------------ grading
def grade(entry_id, grade_name, token, day=None, revise=False):
    """Record one answer. Returns a dict describing what actually happened.

    Idempotent: the same token twice leaves the database exactly as the first
    call left it, and reports counted=False the second time.

    revise=True is the "反悔" path -- the user has just seen the answer and is
    correcting the grade they gave a moment ago. The earlier answer's ease step
    is backed out first, so changing 认识 to 不认识 lands on the same ease as
    answering 不认识 straight away rather than netting the two together.
    """
    if grade_name not in srs.GRADES:
        raise ValueError("unknown grade %r" % (grade_name,))
    day = day or today()
    c = conn()
    with c:                                    # BEGIN ... COMMIT / ROLLBACK
        c.execute("BEGIN IMMEDIATE")
        dup = c.execute("SELECT 1 FROM reviews WHERE token=?", (token,)).fetchone()
        if dup:
            return {"ok": True, "duplicate": True, "counted": False,
                    "lapsed": False, "day_count": _day_count(c, day)}

        row = c.execute("SELECT * FROM cards WHERE entry_id=?", (entry_id,)).fetchone()
        was_new = row is None
        reps, interval, ease = (0, 0, srs.EASE_START) if was_new else (
            row["reps"], row["interval"], row["ease"])

        if revise and not was_new:
            prev = c.execute("SELECT grade FROM reviews WHERE day=? AND entry_id=? "
                             "ORDER BY ts DESC LIMIT 1", (day, entry_id)).fetchone()
            if prev:
                ease = srs.clamp(ease - srs.EASE_STEP[prev["grade"]],
                                 srs.EASE_MIN, srs.EASE_MAX)

        # Did this word already count today? (relearning must not count twice)
        seen_today = c.execute(
            "SELECT 1 FROM reviews WHERE day=? AND entry_id=? LIMIT 1",
            (day, entry_id)).fetchone() is not None

        reps, interval, ease, lapsed = srs.schedule(reps, interval, ease, grade_name)
        due = (date.fromisoformat(day) + timedelta(days=max(interval, 0))).isoformat()

        if was_new:
            c.execute("INSERT INTO cards (entry_id,reps,interval,ease,due,lapses,"
                      "first_seen,last_seen) VALUES (?,?,?,?,?,?,?,?)",
                      (entry_id, reps, interval, ease, due, 1 if lapsed else 0, day, day))
        else:
            c.execute("UPDATE cards SET reps=?,interval=?,ease=?,due=?,"
                      "lapses=lapses+?,last_seen=? WHERE entry_id=?",
                      (reps, interval, ease, due, 1 if lapsed else 0, day, entry_id))

        c.execute("INSERT INTO reviews (token,entry_id,day,grade,was_new,ts) "
                  "VALUES (?,?,?,?,?,?)",
                  (token, entry_id, day, grade_name, 1 if was_new else 0, time.time()))
        c.execute("INSERT OR IGNORE INTO daily (day,goal) VALUES (?,?)", (day, DAILY_GOAL))

        return {"ok": True, "duplicate": False, "counted": not seen_today,
                "lapsed": lapsed, "day_count": _day_count(c, day)}


def _day_count(c, day):
    return c.execute("SELECT COUNT(DISTINCT entry_id) FROM reviews WHERE day=?",
                     (day,)).fetchone()[0]


def _extra_round_counts(c, day, day_count, goal=DAILY_GOAL):
    """(recorded, displayed) extra rounds for one day.

    Older progress has no round events.  In that case the completed words over
    the daily goal still provide a useful whole-round estimate.  Keeping the
    larger value also prevents that inferred history disappearing as soon as a
    newly completed round writes the day's first event.
    """
    recorded = c.execute(
        "SELECT COUNT(*) FROM extra_rounds WHERE day=?", (day,)).fetchone()[0]
    inferred = max(0, (day_count - goal) // EXTRA_SIZE)
    return recorded, max(recorded, inferred)


def celebrate_once(day=None):
    """True exactly once, on the call that first sees the goal met."""
    day = day or today()
    c = conn()
    with c:
        c.execute("BEGIN IMMEDIATE")
        c.execute("INSERT OR IGNORE INTO daily (day,goal) VALUES (?,?)", (day, DAILY_GOAL))
        row = c.execute("SELECT goal,celebrated FROM daily WHERE day=?", (day,)).fetchone()
        if row["celebrated"] or _day_count(c, day) < row["goal"]:
            return False
        c.execute("UPDATE daily SET celebrated=1 WHERE day=?", (day,))
        return True


def complete_extra_round(token, day=None, size=EXTRA_SIZE):
    """Persist one completed extra round and return today's extra-round count.

    ``token`` is stable for the lifetime of the round, which makes this safe to
    retry.  ``day`` is the server date on which the round started, so finishing
    across midnight still credits the intended study day.
    """
    token = str(token or "").strip()[:200]
    if not token:
        raise ValueError("an extra-round token is required")
    day = str(day or today())[:10]
    try:
        date.fromisoformat(day)
    except ValueError:
        raise ValueError("not a YYYY-MM-DD date: %r" % day)
    size = int(size)
    if size < 1 or size > EXTRA_SIZE:
        raise ValueError("extra-round size must be between 1 and %d" % EXTRA_SIZE)

    c = conn()
    with c:
        c.execute("BEGIN IMMEDIATE")
        existing = c.execute(
            "SELECT day FROM extra_rounds WHERE token=?", (token,)).fetchone()
        if existing:
            recorded_day = existing["day"]
            goal_row = c.execute(
                "SELECT goal FROM daily WHERE day=?", (recorded_day,)).fetchone()
            recorded_goal = goal_row["goal"] if goal_row else DAILY_GOAL
            recorded, count = _extra_round_counts(
                c, recorded_day, _day_count(c, recorded_day), recorded_goal)
            return {"ok": True, "counted": False, "duplicate": True,
                    "recorded_day": recorded_day,
                    "extra_rounds_recorded": recorded,
                    "extra_rounds_today": count}
        goal_row = c.execute("SELECT goal FROM daily WHERE day=?", (day,)).fetchone()
        goal = goal_row["goal"] if goal_row else DAILY_GOAL
        if _day_count(c, day) < goal:
            raise ValueError("the daily goal must be completed before an extra round")
        cur = c.execute(
            "INSERT OR IGNORE INTO extra_rounds (token,day,size,ts) VALUES (?,?,?,?)",
            (token, day, size, time.time()))
        recorded, count = _extra_round_counts(c, day, _day_count(c, day), goal)
        return {"ok": True, "counted": cur.rowcount == 1,
                "duplicate": cur.rowcount == 0, "recorded_day": day,
                "extra_rounds_recorded": recorded,
                "extra_rounds_today": count}


# ------------------------------------------------------------------ queue
def build_queue(all_entry_ids, day=None, goal=DAILY_GOAL, min_new=MIN_NEW, rng=random,
                extra=False):
    """The cards to study now, shuffled.

    Reserves min_new of the day's goal for unseen words, gives the rest to due
    reviews, and hands any unused review slots back to new words.

    extra=True builds a whole round on top of a day whose goal is already met:
    goal is then the size of that round rather than a ceiling for the day, and
    its new-word quota starts fresh. Cards already answered today are still
    excluded, so a bonus round never re-serves them.
    """
    day = day or today()
    c = conn()
    done = {r[0] for r in c.execute(
        "SELECT DISTINCT entry_id FROM reviews WHERE day=?", (day,))}

    if extra:
        remaining, new_done = goal, 0
    else:
        remaining = goal - len(done)
        if remaining <= 0:
            return []
        new_done = c.execute(
            "SELECT COUNT(DISTINCT entry_id) FROM reviews WHERE day=? AND was_new=1",
            (day,)).fetchone()[0]

    due = [r[0] for r in c.execute(
        "SELECT entry_id FROM cards WHERE due<=? ORDER BY due", (day,))
        if r[0] not in done]
    rng.shuffle(due)

    seen = {r[0] for r in c.execute("SELECT entry_id FROM cards")}
    unseen = [e for e in all_entry_ids if e not in seen and e not in done]
    rng.shuffle(unseen)

    want_new = max(0, min_new - new_done)
    n_new = min(len(unseen), want_new, remaining)
    take_due = due[:remaining - n_new]
    shortfall = (remaining - n_new) - len(take_due)   # not enough reviews due
    if shortfall > 0:
        n_new = min(len(unseen), n_new + shortfall)

    queue = unseen[:n_new] + take_due
    rng.shuffle(queue)
    return queue


# ------------------------------------------------------------------ stats
def stats(total_entries, day=None, goal=DAILY_GOAL):
    day = day or today()
    c = conn()
    seen = c.execute("SELECT COUNT(*) FROM cards").fetchone()[0]
    mastered = c.execute("SELECT COUNT(*) FROM cards WHERE interval>=?",
                         (srs.MASTERED_DAYS,)).fetchone()[0]
    due_now = c.execute("SELECT COUNT(*) FROM cards WHERE due<=?", (day,)).fetchone()[0]
    # day has to be threaded through: with it defaulting to the real today, a
    # stats() call for any other date reported a streak of 0.
    hist = history(day=day)
    achieved = sum(1 for d, n in hist.items() if n >= goal)
    today_count = hist.get(day, 0)
    extra_rounds_recorded, extra_rounds_today = _extra_round_counts(
        c, day, today_count, goal)
    return {
        "day": day,
        "seen": seen, "total": total_entries, "unseen": total_entries - seen,
        "mastered": mastered, "learning": seen - mastered,
        "due_now": due_now,
        "today": today_count, "goal": goal,
        "extra_rounds_recorded": extra_rounds_recorded,
        "extra_rounds_estimated": extra_rounds_today > extra_rounds_recorded,
        "extra_rounds_today": extra_rounds_today,
        "days_achieved": achieved,
        "streak": streak(hist, goal, day), "best_streak": best_streak(hist, goal),
    }


def history(days=365, day=None):
    """{'YYYY-MM-DD': distinct cards done} for the heatmap."""
    day = day or today()
    if days is None:
        return {r["day"]: r["n"] for r in conn().execute(
            "SELECT day, COUNT(DISTINCT entry_id) n FROM reviews GROUP BY day")}
    start = (date.fromisoformat(day) - timedelta(days=days - 1)).isoformat()
    return {r["day"]: r["n"] for r in conn().execute(
        "SELECT day, COUNT(DISTINCT entry_id) n FROM reviews "
        "WHERE day>=? GROUP BY day", (start,))}


def streak(hist, goal=DAILY_GOAL, day=None):
    """Consecutive days meeting the goal, counting back. Today not yet met does
    not break it -- the day is still in progress."""
    d = date.fromisoformat(day or today())
    if hist.get(d.isoformat(), 0) < goal:
        d -= timedelta(days=1)
    n = 0
    while hist.get(d.isoformat(), 0) >= goal:
        n += 1
        d -= timedelta(days=1)
    return n


def best_streak(hist, goal=DAILY_GOAL):
    days = sorted(d for d, n in hist.items() if n >= goal)
    best = run = 0
    prev = None
    for s in days:
        cur = date.fromisoformat(s)
        run = run + 1 if prev and (cur - prev).days == 1 else 1
        best = max(best, run)
        prev = cur
    return best


def export():
    c = conn()
    return {
        "schema_version": 2,
        "exported": time.time(),
        "cards": [dict(r) for r in c.execute("SELECT * FROM cards")],
        "reviews": [dict(r) for r in c.execute("SELECT * FROM reviews")],
        "daily": [dict(r) for r in c.execute("SELECT * FROM daily")],
        "extra_rounds": [dict(r) for r in c.execute("SELECT * FROM extra_rounds")],
    }


# ------------------------------------------------------------------ import
MAX_ROWS = 500000         # a sane ceiling; a real export is far smaller
_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _as_day(v):
    v = str(v)[:10]
    if not _DATE_RE.match(v):
        raise ValueError("not a YYYY-MM-DD date: %r" % v)
    return v


def _rows(payload, key):
    v = payload.get(key, [])
    if not isinstance(v, list):
        raise ValueError("%s must be a list" % key)
    if len(v) > MAX_ROWS:
        raise ValueError("%s has %d rows, over the %d limit" % (key, len(v), MAX_ROWS))
    return v


def inspect(payload):
    """What an uploaded file claims to hold, without touching the database."""
    if not isinstance(payload, dict):
        raise ValueError("that file is not a progress export")
    for k in ("cards", "reviews"):
        if k not in payload:
            raise ValueError("missing '%s' -- is this a progress export?" % k)
    return {"cards": len(_rows(payload, "cards")),
            "reviews": len(_rows(payload, "reviews")),
            "daily": len(_rows(payload, "daily")),
            "extra_rounds": len(_rows(payload, "extra_rounds")),
            "exported": payload.get("exported")}


def backup_to(path):
    """A consistent copy of the live database, WAL and all."""
    dst = sqlite3.connect(str(path))
    try:
        with dst:
            conn().backup(dst)
    finally:
        dst.close()
    return path


def import_progress(payload, valid_ids=None):
    """Replace all progress with the contents of an export.

    Replace rather than merge: this is the other half of the export button, and
    a restore that silently blended two histories would be impossible to reason
    about. The current database is copied aside first, so an import of the wrong
    file is undoable.

    Every value is coerced and range-checked here -- the payload is a file the
    user picked, so it is untrusted input, and it only ever reaches sqlite
    through bound parameters.
    """
    counts = inspect(payload)

    cards, reviews, daily, extra_rounds = [], [], [], []
    for r in _rows(payload, "cards"):
        eid = int(r["entry_id"])
        if valid_ids is not None and eid not in valid_ids:
            continue                     # a word this vocabulary no longer has
        cards.append((eid, max(0, int(r.get("reps", 0))), max(0, int(r.get("interval", 0))),
                      srs.clamp(float(r.get("ease", srs.EASE_START)),
                                srs.EASE_MIN, srs.EASE_MAX),
                      _as_day(r.get("due", today())), max(0, int(r.get("lapses", 0))),
                      _as_day(r.get("first_seen", today())),
                      _as_day(r.get("last_seen", today()))))
    for r in _rows(payload, "reviews"):
        eid = int(r["entry_id"])
        if valid_ids is not None and eid not in valid_ids:
            continue
        g = str(r.get("grade", ""))
        if g not in srs.GRADES:
            continue                     # drop rows we cannot interpret
        token = str(r["token"])[:200]
        reviews.append((token, eid, _as_day(r.get("day", today())), g,
                        1 if r.get("was_new") else 0, float(r.get("ts", 0) or 0)))
    for r in _rows(payload, "daily"):
        daily.append((_as_day(r["day"]), max(1, int(r.get("goal", DAILY_GOAL))),
                      1 if r.get("celebrated") else 0))
    extra_tokens = set()
    for r in _rows(payload, "extra_rounds"):
        token = str(r.get("token") or "").strip()[:200]
        if not token or token in extra_tokens:
            continue
        size = int(r.get("size", EXTRA_SIZE))
        if size < 1 or size > 10000:
            continue
        extra_tokens.add(token)
        extra_rounds.append((token, _as_day(r.get("day", today())), size,
                             float(r.get("ts", 0) or 0)))

    backup = DATA_DIR / ("progress-before-import-%s.db" % time.strftime("%Y%m%d-%H%M%S"))
    backup_to(backup)

    c = conn()
    with c:
        c.execute("BEGIN IMMEDIATE")
        c.execute("DELETE FROM cards")
        c.execute("DELETE FROM reviews")
        c.execute("DELETE FROM daily")
        c.execute("DELETE FROM extra_rounds")
        c.executemany("INSERT OR REPLACE INTO cards (entry_id,reps,interval,ease,due,"
                      "lapses,first_seen,last_seen) VALUES (?,?,?,?,?,?,?,?)", cards)
        c.executemany("INSERT OR IGNORE INTO reviews (token,entry_id,day,grade,was_new,ts)"
                      " VALUES (?,?,?,?,?,?)", reviews)
        c.executemany("INSERT OR REPLACE INTO daily (day,goal,celebrated) VALUES (?,?,?)",
                      daily)
        c.executemany("INSERT OR IGNORE INTO extra_rounds (token,day,size,ts) "
                      "VALUES (?,?,?,?)", extra_rounds)

    return {"ok": True, "backup": backup.name,
            "in_file": counts,
            "imported": {"cards": len(cards), "reviews": len(reviews), "daily": len(daily),
                         "extra_rounds": len(extra_rounds)},
            "skipped": {"cards": counts["cards"] - len(cards),
                        "reviews": counts["reviews"] - len(reviews),
                        "extra_rounds": counts["extra_rounds"] - len(extra_rounds)}}


if __name__ == "__main__":
    import os
    DB_PATH = DATA_DIR / "selftest.db"

    def wipe():
        c = getattr(_local, "conn", None)
        if c is not None:      # Windows will not unlink a file sqlite still holds
            c.close()
            _local.conn = None
        for suffix in ("", "-wal", "-shm"):
            p = Path(str(DB_PATH) + suffix)
            if p.exists():
                os.remove(p)

    def fresh():
        """Each scenario starts from an empty database, so one cannot leave a
        backlog that quietly invalidates the next."""
        wipe()
        init()

    def seed_due(entry_ids, due_day):
        c = conn()
        with c:
            for e in entry_ids:
                c.execute("INSERT OR REPLACE INTO cards (entry_id,reps,interval,ease,"
                          "due,lapses,first_seen,last_seen) VALUES (?,?,?,?,?,?,?,?)",
                          (e, 3, 5, 2.5, due_day, 0, due_day, due_day))

    fresh()
    ALL = list(range(1, 1001))
    D = "2026-01-01"

    q = build_queue(ALL, day=D)
    assert len(q) == DAILY_GOAL, len(q)
    assert len(set(q)) == len(q), "queue must not repeat a card"
    print("fresh queue:", len(q), "cards, all new (nothing is due yet)")

    r = grade(q[0], srs.GOOD, "tok-1", day=D)
    assert r["counted"] and not r["duplicate"], r
    # idempotency: same token again changes nothing
    r2 = grade(q[0], srs.GOOD, "tok-1", day=D)
    assert r2["duplicate"] and not r2["counted"], r2
    assert r["day_count"] == r2["day_count"] == 1
    print("idempotent  : replaying a token leaves day_count at", r2["day_count"])

    # relearning the same word on the same day must not count twice
    r3 = grade(q[0], srs.AGAIN, "tok-2", day=D)
    assert not r3["counted"] and r3["lapsed"], r3
    assert _day_count(conn(), D) == 1
    print("relearn     : second answer on the same word keeps day_count at 1")

    # 反悔: 认识 then correcting to 不认识 must land where a plain 不认识 would,
    # not net the two ease steps against each other.
    w = q[1]
    grade(w, srs.GOOD, "rev-a", day=D)
    grade(w, srs.AGAIN, "rev-b", day=D, revise=True)
    row = conn().execute("SELECT * FROM cards WHERE entry_id=?", (w,)).fetchone()
    direct = srs.schedule(0, 0, srs.EASE_START, srs.AGAIN)
    assert (row["reps"], row["interval"]) == (0, 0), dict(row)
    assert abs(row["ease"] - direct[2]) < 1e-9, (row["ease"], direct[2])
    assert _day_count(conn(), D) == 2, "a revision must not add to the daily count"
    print("revise      : 认识→不认识 gives ease %.2f, same as answering 不认识 directly"
          % row["ease"])

    for i, e in enumerate(q[1:60], start=2):
        grade(e, srs.GOOD, "t%d" % i, day=D)
    assert _day_count(conn(), D) == 60

    # 60 done today, so the queue tops up to the goal and never re-serves them
    q2 = build_queue(ALL, day=D)
    assert len(q2) == DAILY_GOAL - 60, len(q2)
    assert not ({q[0]} & set(q2)), "a card already done today came back"
    print("top-up      :", len(q2), "more to reach the goal, no repeats")

    # Celebration fires once and only once.
    for i, e in enumerate(q2, start=1000):
        grade(e, srs.GOOD, "c%d" % i, day=D)
    assert _day_count(conn(), D) == DAILY_GOAL
    assert celebrate_once(day=D) is True
    assert celebrate_once(day=D) is False
    print("celebration : fires once at", DAILY_GOAL, "then never again that day")

    # An extra round on top of a finished day: full size, its own new-word
    # quota, and never re-serving anything already answered today.
    doneToday = {r[0] for r in conn().execute(
        "SELECT DISTINCT entry_id FROM reviews WHERE day=?", (D,))}
    bonus = build_queue(ALL, day=D, goal=EXTRA_SIZE, min_new=EXTRA_NEW, extra=True)
    seenNow = {r[0] for r in conn().execute("SELECT entry_id FROM cards")}
    bonusNew = [e for e in bonus if e not in seenNow]
    assert len(bonus) == EXTRA_SIZE, len(bonus)
    assert not (set(bonus) & doneToday), "a bonus round re-served today's cards"
    assert len(bonusNew) == EXTRA_NEW, "bonus round is not all new: %d" % len(bonusNew)
    assert build_queue(ALL, day=D) == [], "the normal queue must still be finished"
    print("extra round : %d cards (%d new) after the goal, no repeats of today"
          % (len(bonus), len(bonusNew)))

    h = history(day=D)
    assert h[D] == DAILY_GOAL
    assert streak(h, day=D) == 1
    s = stats(9368, day=D)
    assert s["seen"] == DAILY_GOAL, s["seen"]
    print("stats       : seen %d/%d, mastered %d, today %d/%d, streak %d"
          % (s["seen"], s["total"], s["mastered"], s["today"], s["goal"], s["streak"]))

    # Breadth, on its own database: a huge backlog must not starve new words.
    fresh()
    D2 = "2026-06-01"
    seed_due(range(1, 400), "2026-05-01")          # 399 already overdue
    q3 = build_queue(ALL, day=D2)
    seen_ids = {r[0] for r in conn().execute("SELECT entry_id FROM cards")}
    new3 = [e for e in q3 if e not in seen_ids]
    assert len(q3) == DAILY_GOAL, len(q3)
    assert len(new3) >= MIN_NEW, "reviews starved new words: only %d new" % len(new3)
    print("breadth     : 399 due -> %d new + %d review in a %d card day"
          % (len(new3), len(q3) - len(new3), len(q3)))

    # Spare review slots go to new words rather than going unused.
    fresh()
    D3 = "2026-06-01"
    seed_due(range(1, 11), "2026-05-01")           # only 10 due
    q4 = build_queue(ALL, day=D3)
    seen4 = {r[0] for r in conn().execute("SELECT entry_id FROM cards")}
    new4 = [e for e in q4 if e not in seen4]
    assert len(q4) == DAILY_GOAL, len(q4)
    assert len(new4) == DAILY_GOAL - 10, len(new4)
    print("spare slots : 10 due -> %d new + 10 review, nothing wasted" % len(new4))

    # Nothing left to learn: the day is reviews only, and stays within the goal.
    fresh()
    seed_due(ALL, "2026-05-01")
    q5 = build_queue(ALL, day="2026-06-01")
    assert len(q5) == DAILY_GOAL and not set(q5) - set(ALL)
    print("all seen    : queue falls back to %d reviews" % len(q5))

    # Export -> wipe -> import must round-trip exactly.
    fresh()
    D4 = "2026-03-03"
    for i, e in enumerate(build_queue(ALL, day=D4)[:25], start=1):
        grade(e, srs.GOOD if i % 2 else srs.HARD, "rt-%d" % i, day=D4)
    before = (stats(1000, day=D4), export())
    snapshot = json.loads(json.dumps(before[1]))      # as it would travel over HTTP

    fresh()
    assert stats(1000, day=D4)["seen"] == 0
    res = import_progress(snapshot, valid_ids=set(ALL))
    after = stats(1000, day=D4)
    assert after["seen"] == before[0]["seen"], (after["seen"], before[0]["seen"])
    assert after["today"] == before[0]["today"]
    assert after["mastered"] == before[0]["mastered"]
    assert res["imported"]["reviews"] == len(before[1]["reviews"])
    print("import      : round-trip restored %d cards / %d reviews (backup %s)"
          % (res["imported"]["cards"], res["imported"]["reviews"], res["backup"]))

    # Rows for words this vocabulary does not have are dropped, not imported.
    res2 = import_progress(snapshot, valid_ids={1, 2, 3})
    assert res2["imported"]["cards"] <= 3, res2
    assert res2["skipped"]["cards"] >= 1
    print("import      : %d unknown cards skipped when the vocabulary is smaller"
          % res2["skipped"]["cards"])

    # Anything that is not an export is refused before the database is touched.
    for bad in ({}, {"cards": []}, "nonsense", {"cards": [], "reviews": "no"}):
        try:
            inspect(bad)
        except (ValueError, AttributeError):
            pass
        else:
            raise AssertionError("accepted a bad payload: %r" % (bad,))
    print("import      : malformed files rejected")

    for f in DATA_DIR.glob("progress-before-import-*.db"):
        os.remove(f)
    wipe()
    print("store: all assertions passed")
